name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 *44 * * *'

jobs:
  run-python-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install unzip & python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        pip install requests

    - name: Un File
      env:
        ZIP_FILE: ${{ secrets.ZIP_FILE }}
      run: unzip -P "${ZIP_FILE}" 2mainmy.zip

    - name: Run Python script
      env:
        API_URL: ${{ secrets.API_URL }}
      run: python3 2mainmy.py

    - name: Delete Python script after run (always)
      if: always()
      run: rm -f 2mainmy.py || true

    - name: Clone target repository
      run: |
        git clone https://x-access-token:${{ secrets.GET_API_TOKEN }}@${{ secrets.GET_URL }} target-repo

    - name: Copy generated files to target repo
      run: |
        cp *.m3u target-repo/
        mkdir -p target-repo/script_api
        cp script_api/data.json target-repo/script_api/

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "Update playlists and api.json [$(date '+%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
        git push
